title: "Agha Sultan Naseer"
description: "Meta & Google Ads Strategist. Turning ad spend into profit."
url: ""
baseurl: ""
theme: # Blank
markdown: kramdown
permalink: /blog/:title/
exclude: ["node_modules", "package.json", "package-lock.json", "playwright.config.ts", "tests", "README.md"]
